# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - padronas@stanford.edu
            - su2code-dev@lists.stanford.edu
        on_success: never
        on_failure: always
  
branches:
    only:
        - develop

env:
    global:
        CXXFLAGS=-O3
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./configure --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        - CONFIGURE_COMMAND="./configure --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=parallel_regression.py

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2

install:
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 8
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git
    - cd TestCases/
    - git checkout develop

script:
    # run the tests
    python $TEST_SCRIPT

